### PR TITLE
enforce repo sync, but only when sensible

### PR DESCRIPTION
**Pull request by bru**
This forces a fetch from the remote whenever a `cplus` command is issued
and the local repository is over threshold (currently 2 hours old).
The check takes close to no time, so it doesn't impact the normal
operations; if the repo is due a sync, that is actioned immediately: it
takes a few seconds and will potentially save a lot of headaches.
As an improvement, we may make the sync optional, introducing a setting
to opt out of the automatic sync, in favour of a warning message.

### CODE REVIEW

**Comment by lackac** [comment]
Is it repetition that you're trying to avoid with this change?

I think there are two issues with doing the sync for every command:

1. it makes it implicit which could lead to confusion when developing new commands
2. not all commands need to be in the CollectPlus repo to work (e.g. `ips`, `remote`, etc.), for some it might be even counterproductive to change there (e.g. `pair`)

**Comment by bru** [comment]
nope, what I'm trying to address is what I described above: saving headaches in case of last minute changes to the repo, especially when assembling releases or doing a lot of code reviews (which means jumping from branch to branch, all of which are likely to have been recently worked on).

**Comment by bru** [comment]
but the repo constraint is something I did forgot about, and wanted to make it a point of the PR. why would forcing the cwd to be the project be counterproductive for `pair`?

**Comment by lackac** [comment]
`pair` could be used in repos other than the main one but if the script changes directory, the git config will be set in an unexpected place and have no effect on the user's cwd.

**Comment by lackac** [comment]
I would prefer having that extra two lines explicitly in every command that benefits from a freshly fetched rep.

**Comment by bru** [comment]
or keep running the following in another terminal, which is what I do at the moment :) 
```
for (( ; ; ))
do
   cplus update
   sleep 15
done
```

**Comment by bru** [comment]
this is now obsolete, so happy to close it.
for whoever is afraid like me of being caught by an outdated repo: I built this same functionality outside of the tool by forcing a git fetch every minute or so using a LaunchAgent (works like cron, but with xml, thanks Apple).

**Pull request closed without merging**
